### ISSUE TITLE
Got HTTP status code >= 400: 500 Internal Server Error

### ISSUE THREAD

**Issue by hldh214** [arukasio/cli#47]
Got HTTP status code >= 400: 500 Internal Server Error

**Comment by dopin** [comment]
Can you write more information?

**Comment by hldh214** [comment]
cli tool:
root@69289cc897ca:~# ./arukas ps
2017/01/27 02:26:41 Got HTTP status code >= 400: 500 Internal Server Error
root@69289cc897ca:~# 

postman:
{
  "status": "500",
  "error": "Internal Server Error"
}

**Comment by dopin** [comment]
It's working now. Thank you for reporting.
