### ISSUE TITLE
how to run container with additional docker options?

### ISSUE THREAD

**Issue by hbakhtiyor** [arukasio/cli#58]
e.g. 

```
docker run --shm-size=1024m --cap-add=SYS_ADMIN --security-opt seccomp:/path
```

how to pass the options to arukas?

**Comment by uzyexe** [comment]
@hbakhtiyor 

Does not support those options.

Arukas is a shared hosting service that shares server resources with other customers. Can not flexibly change the size and function of shm.
The reason is to avoid impacting other containers of other customers on the same host.
